EmployeeManagement/Controllers/CarController.cs
using System;
using System.Linq;
using cloudscribe.Pagination.Models;
using EmployeeManagement.Models;
using EmployeeManagement.Service.Interfaces;
using EmployeeManagement.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System.IO;
using EmployeeManagement.Service.Infrastructures;
using Microsoft.AspNetCore.Hosting;

namespace EmployeeManagement.Controllers
{
    public class CarController : Controller
    {
        private readonly ICar _car;
        private readonly IHostingEnvironment _hostingEnvironment;

        public CarController(ICar car, IHostingEnvironment hostingEnvironment)
        {
            _car = car;
            _hostingEnvironment = hostingEnvironment;
        }

        [HttpGet]
        public IActionResult Index(int pageNumber = 1, int pageSize = 3)
        {
            int ExcludeRecords = (pageSize * pageNumber) - pageSize;

            var empList = _car.GetCars(true)
                .Skip(ExcludeRecords)
                .Take(pageSize);

            var result = new PagedResult<Car>
            {
                Data = empList.ToList(),
                TotalItems = _car.GetCars().Count(),
                PageNumber = pageNumber,
                PageSize = pageSize
            };

            return View(result);
        }

        [HttpGet]
        public ViewResult Details(int? id)
        {
            Car car = _car.GetCar(id.Value);

            if (car == null)
            {
                return View("EmployeeNotFound", id.Value);
            }

            CarViewModel carViewModel = new CarViewModel()
            {
                Car = car,
                PageTitle = "Car View"
            };

            return View(carViewModel);
        }

        [HttpGet]
        public ViewResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Car obj)
        {
            if (ModelState.IsValid)
            {
                Car car = new Car()
                {
                    Manufacturer = obj.Manufacturer,
                    Model = obj.Model,
                    Year = obj.Year,
                    ProducingCountry = obj.ProducingCountry
                };

                _car.Add(car);
                return RedirectToAction("Details", new { id = car.Id });
            }

            return View("Create");
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            Car car = _car.GetCar(id);

            if (car != null)
            {
                //CarViewModel carViewModel = new CarViewModel();
                //carViewModel.Car = car;
                //carViewModel.PageTitle = "Details view | Edit";
                return View(car);
            }

            return RedirectToAction("index");
        }

        [HttpPost]
        public IActionResult Edit(Car obj)
        {
            //Car car = _car.GetCar(obj.Id);
            //car.Manufacturer = obj.Manufacturer;
            //car.Model = obj.Model;
            //car.ProducingCountry = obj.ProducingCountry;
            //car.Year = obj.Year;

            _car.Update(obj);
            return RedirectToAction("Details", new { id = obj.Id });
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            if (_car.Delete(id))
            {
                return RedirectToAction("index");
            }
            return RedirectToAction("Create");
        }

        [HttpGet]
        public JsonResult CarManufacturer()
        {
            return Json(_car.GetCars());
        }

        [HttpGet]
        public IActionResult UploadViaCSV()
        {
            return View();
        }

        public IActionResult UploadViaCSV(CSVViewModel model)
        {
            try
            {
                var path = ProcessUploadFile(model);
                var resultData = new CarService().ReadCSVFile(path);
                foreach (var item in resultData)
                {
                    _car.Add(item);
                }
                return RedirectToAction("index");
            }
            catch(Exception)
            {
                return RedirectToAction("Error", "Error", new { });
            }
        }

        private string ProcessUploadFile(CSVViewModel filePath)
        {
            string uniqueFileName = null;

            if (filePath.filePath != null)
            {
                string uploadsFolder = Path.Combine(_hostingEnvironment.WebRootPath, "csv");
                uniqueFileName = Guid.NewGuid().ToString() + "_" + filePath.filePath.FileName;

                string filePath2 = Path.Combine(uploadsFolder, uniqueFileName);

                using (var fileStream = new FileStream(filePath2, FileMode.Create))
                {
                    filePath.filePath.CopyTo(fileStream);
                }

                uniqueFileName = filePath2;
            }

            return uniqueFileName;
        }
    }
}

EmployeeManagement/Views/Shared/NotFound.cshtml
@{
    ViewBag.Title = "Not Found";
}

    <h1>@ViewBag.ErrorMessage</h1>

<a asp-controller="home" asp-action="getall">
    Click here to naviagate the home controller
</a>

EmployeeManagement/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.PageTitle</title>
    <link rel="icon" type="image/x-icon" href="~/favicon/favicon.ico">
    <environment include="Development">
        <link href="~/lib/bootstrap/css/bootstrap.css" rel="stylesheet" />
        <script src="~/lib/jquery/jquery.js"></script>
        <script src="~/lib/bootstrap/js/bootstrap.js"></script>
        @RenderSection("Styles", required: false)
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
              crossorigin="anonymous"
              asp-fallback-href="~/lib/bootstrap/css/bootstrap.css"
              asp-fallback-test-class="sr-only"
              asp-fallback-test-property="position"
              asp-fallback-test-value="absolute"
              asp-suppress-fallback-integrity="true">
        @RenderSection("Styles", required: false)
    </environment>
    <link href="~/css/customfooter.css" rel="stylesheet" />
    <script src="~/lib/jquery/jquery.js"></script>
</head>
<body>
    <div class="container">
        <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
            <a class="navbar-brand" asp-controller="Home" asp-action="GetAll">
                <img src="~/images/logo.png" height="30" width="30" asp-append-version="true" />
                <span class="active text-danger">EMS | </span>
            </a>
            <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#collapsibleNavbar">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="collapsibleNavbar">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a asp-controller="Home" asp-action="GetAll" class="nav-link">List</a>
                    </li>
                    @*<li class="nav-item">
                            <a asp-controller="Home" asp-action="Create" class="nav-link">Create</a>
                        </li>*@
                    <li class="nav-item">
                        <a asp-controller="Account" asp-action="Register" class="nav-link">Register</a>
                    </li>
                    <li class="nav-item">
                        <a asp-controller="Car" asp-action="Index" class="nav-link">Cars</a>
                    </li>
                </ul>
            </div>
        </nav>
        <div>
            @RenderBody()
        </div>

        <hr />

        <footer class="new_footer_area bg_color">
            <div class="new_footer_top">
                <div class="container">
                    <div class="row">

                        <div class="col-lg-3 col-md-6">
                            <div class="f_widget social-widget pl_70 wow fadeInLeft" data-wow-delay="0.8s" style="visibility: visible; animation-delay: 0.8s; animation-name: fadeInLeft;">
                                <h3 class="f-title f_600 t_color f_size_18">Team Solutions</h3>
                                <div class="f_social_icon">
                                    <a href="#" class="fab fa-facebook"></a>
                                    <a href="#" class="fab fa-twitter"></a>
                                    <a href="#" class="fab fa-linkedin"></a>
                                    <a href="#" class="fab fa-pinterest"></a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="footer_bg">
                    <div class="footer_bg_one"></div>
                    <div class="footer_bg_two"></div>
                </div>
            </div>
            <div class="footer_bottom">
                <div class="container">
                    <div class="row align-items-center">
                        <div class="col-lg-6 col-sm-7">
                            <p class="mb-0 f_400">© 2019 All rights reserved | Ashraful Alam</p>
                        </div>
                        <div class="col-lg-6 col-sm-5 text-right">
                            <p>Made with <i class="icon_heart"></i> in <a asp-controller="Home" asp-action="GetAll">公平</a></p>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
    </div>

    @RenderSection("Scripts", required: false)
</body>
</html>

EmployeeManagement/Views/Shared/_PaginationPartial.cshtml
<cs-pager cs-paging-pagenumber=(int)Model.PageNumber
          cs-paging-totalitems=(int)Model.TotalItems
          cs-paging-pagesize=Model.PageSize
          cs-pagenumber-param="pagenumber"
          asp-controller="@ViewData["controller"]"
          asp-action="@ViewData["action"]"
          cs-pager-li-current-class="page-item active"
          cs-pager-li-other-class="page-item"
          cs-pager-li-non-active-class="pager-item disabled"
          cs-pager-link-current-class="page-link"
          cs-pager-link-other-class="page-link"></cs-pager>